server:
  port: 10001

management:
  tracing:
    sampling:
      probability: 0.0

logging:
  config: classpath:logback-dev.xml

jwt:
  secret: ENC(xDFjyXzNIV+adO35+9y/ZjMZjLok9UYrFDyQdJrfEFbu8bgbkHJV+q6gKTa/2oK92G0b8sGyO7O6PngLR4ZhJA47X1TmsvC2m6TL76nl3w8=)
  expiration: 3600000

spring:
  datasource:
    url: ENC(uoWzLGEXp7+Q++PfhmDmRYdFF2XyvG8Rd8xx7B5cq9FT7kF/ce6HSSClOjtxvSa7)
    username: ENC(kInVu3qE8YAC209gh6I7nA==)
    password: ENC(kInVu3qE8YAC209gh6I7nA==)
    driver-class-name: org.mariadb.jdbc.Driver

mybatis:
  mapper-locations: classpath:xyz/outerringroad/redbull/mapper/*.xml

jasypt:
  encryptor:
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
